name: Docker Image CI

on: [push]

jobs:
  build-docker-image:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          cd alpine-nginx-php-fpm-for-transmisson/ssl
          ./selfssl.sh
          cd ..
          docker build . --file Dockerfile --tag alpine-nginx-php-fpm-for-transmisson:$(date +%s)
