name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run: git checkout HEAD^
    - name: init ssl
      run: ./selfssl.sh
      working-directory: ./alpine-nginx-php-fpm-for-transmisson
    - name: Build the Docker image
      run: ./alpine-nginx-php-fpm-for-transmisson/selfssl.sh; docker build -t t1 .
      working-directory: ./alpine-nginx-php-fpm-for-transmisson      
