name: Docker Image CI

on: [push]

jobs:
  build-docker-image:
    name: Build and upload docker image
    runs-on: ubuntu-latest
    steps:
      - name: Pull source
        uses: actions/checkout@v2

      - name: Build Docker image
        run: Hello world
